### ISSUE TITLE
主页上的“一键命令安装”无法使用~

### ISSUE THREAD

**Issue by Dicartle** [vastsa/FileCodeBox#100]
在下午15时至今，都无法安装上，我的同学们的VPS系统主要是Debian/Ubuntu，都无法安装这个。

**Comment by Dicartle** [comment]
> 研究了一下，应该是作者文件删多了，等他恢复吧

嗯，今天推荐了同学安装这个，，大家都觉得此软件很有用。但安装不起来，真的是悲伤的事情。

**Comment by vastsa** [comment]
docker pull lanol/filecodebox:beta && docker stop filecodebox && docker rm filecodebox && docker run -d --restart=always -p 12345:12345 -v /opt/FileCodeBox/:/app/data --name filecodebox lanol/filecodebox:beta
执行即可

**Comment by Dicartle** [comment]
> docker pull lanol/filecodebox:beta && docker stop filecodebox && docker rm filecodebox && docker run -d --restart=always -p 12345:12345 -v /opt/FileCodeBox/:/app/data --name filecodebox lanol/filecodebox:beta 执行即可

debian12正常运行，感谢大佬！
