### ISSUE TITLE
docker 最新版 似乎缺少一些文件

### ISSUE THREAD

**Issue by lancer-wang** [vastsa/FileCodeBox#101]
我到终端看了下，似乎没有./fcb-fronted/dist/index.html 文件
![image](https://github.com/vastsa/FileCodeBox/assets/69783837/f633b0db-be30-4676-a4f5-ecc6ebbe0b84)
![image](https://github.com/vastsa/FileCodeBox/assets/69783837/ecc4e182-d295-4151-9635-40966586f127)

**Comment by lancer-wang** [comment]
看了下commit记录
你是不是多删了点东西。。
![image](https://github.com/vastsa/FileCodeBox/assets/69783837/2c061b08-977a-4dd2-9b31-26ec7de73032)

**Comment by vastsa** [comment]
docker pull lanol/filecodebox:beta && docker stop filecodebox && docker rm filecodebox && docker run -d --restart=always -p 12345:12345 -v /opt/FileCodeBox/:/app/data --name filecodebox lanol/filecodebox:beta
执行即可

**Comment by Dicartle** [comment]
> docker pull lanol/filecodebox:beta && docker stop filecodebox && docker rm filecodebox && docker run -d --restart=always -p 12345:12345 -v /opt/FileCodeBox/:/app/data --name filecodebox lanol/filecodebox:beta 执行即可

debian12经过测试，可以运行，谢谢大佬。
