### ISSUE TITLE
若设置大于1G的，则会完全地崩溃！

### ISSUE THREAD

**Issue by Dicartle** [vastsa/FileCodeBox#102]
系统：Debian 12
版本：最新版
条件：若在后台设置大于1G，即1073741824。
结果：会导致页面完全崩溃，无法再度打开，即使是重启服务器也无法。当打开domain.com:12345时，会提示internal server error。（服务器的空间为50G）
请求：请问大佬，这是否会文件大小或总容量限制？如果可以的话，是否可以设置一个公共区，似ftp那样的列表形式？提供两种获取文件方式，一种是输入码，另一种是点击文件后需要键入密码才能下载？

**Comment by vastsa** [comment]
截图一下docker日志看看

**Comment by vastsa** [comment]
我这边测试没问题
<img width="1177" alt="image" src="https://github.com/vastsa/FileCodeBox/assets/48862574/c41cd5de-896a-4964-bf24-4abdfa43b62f">

**Comment by vastsa** [comment]
公共区的话有考虑，管理员在后台选择文件分享

**Comment by Dicartle** [comment]
> 我这边测试没问题 <img alt="image" width="1177" src="https://user-images.githubusercontent.com/48862574/278184307-c41cd5de-896a-4964-bf24-4abdfa43b62f.png">

收到，请稍等，我今晚回到去再发Log给你。

**Comment by Dicartle** [comment]
> 截图一下docker日志看看

收到，请稍等，我今晚回到去再发Log给你。

**Comment by Dicartle** [comment]
大佬你好，我先发我朋友发现的那个问题给你看看，他说更改了密码为简单的123456之后，就再也不能登录，除非重新安装。他那里就不会出现说修改了储存空间大于1G的字节，无法重连的问题。

**Comment by Dicartle** [comment]
> 截图一下docker日志看看

![QQ截图20231026171639](https://github.com/vastsa/FileCodeBox/assets/55342846/3f3633d3-7a6a-45fa-87fd-15dbd6894f14)
![QQ截图20231026171359](https://github.com/vastsa/FileCodeBox/assets/55342846/e0508bab-dc20-43bf-8d93-4dcbb98f5ba5)
![QQ截图20231026171346](https://github.com/vastsa/FileCodeBox/assets/55342846/27ea353b-ad15-4994-a053-a20fbf5def7b)
