### ISSUE TITLE
关于后台管理密码设置的疑惑

### ISSUE THREAD

**Issue by Dicartle** [vastsa/FileCodeBox#103]
大佬你好，我朋友发现一个问题，他托我过来发给你看看。是把密码修改成简单的，后就无法再登入了，无论是重启系统还是Docker。我之前汇报的问题，设置大于1G的储存字节大小，应该是没有关系的，可能是跟这个有关系。
![QQ截图20231026171346](https://github.com/vastsa/FileCodeBox/assets/55342846/e872c12d-b99b-4dfb-be7a-59b878a77143)
![QQ截图20231026171359](https://github.com/vastsa/FileCodeBox/assets/55342846/913b5aa2-8bd0-4b40-b3eb-5f93c55dc19b)
![QQ截图20231026171639](https://github.com/vastsa/FileCodeBox/assets/55342846/ff07832d-1d16-4ded-b79c-b4ece023488d)

**Comment by Dicartle** [comment]
顺便提一点建议：

**Comment by vastsa** [comment]
发现这个问题了，等我修复

**Comment by Dicartle** [comment]
> 发现这个问题了，等我修复

谢谢大佬。所以我昨晚很纳闷，看日志里是没有问题的，不涉及到储存空间或路径问题，但就是一度出现了提示「internal server error」或「鉴权失败（像以上本问题截图里的提示）」。麻烦大佬了~

**Comment by Dicartle** [comment]
> 因为数字和字符串匹配永远不相等导致，已提交，两点建议我后面写的时候注意一下

感谢大佬！大佬辛苦了。

**Comment by yanxu4780** [comment]
> 顺便提一点建议：1、管理员可以设置访客所分享的方式，允许或禁止某些方式（如永久）这样的；2、酌情增加可编辑的区域，增加一些自定义的文字说明。

我也需要这样的功能，禁止永久链接，否则占用磁盘空间。

**Comment by Do1e** [comment]
#107 中新增了最长保存时间的配置，大于0时生效并禁用永久保存，单位：秒

**Comment by vastsa** [comment]
已更新后台选择允许过期方式
