### ISSUE TITLE
关于取件码的暴刷和页面限制访问

### ISSUE THREAD

**Issue by mp075496706** [vastsa/FileCodeBox#104]
关于安全性的一个讨论。
之前部署了一个不是2.0的版本玩了一下，想到了会不会有暴力破解的可能。
尽管5位数密码的组合很大，但是并发高的情况下来请求，似乎也有这个可能？
不过好像高频访问似乎可以通过第三方的服务来解决，不一定要应用本身去做限制。

**Comment by vastsa** [comment]
系统做了频率限制，错误次数和限流器
