### ISSUE TITLE
您好 请问能首页增加一个进入管理后台的入口吗

### ISSUE THREAD

**Issue by zhroc** [vastsa/FileCodeBox#114]
如题 本人使用该项目主要是自用 所以关闭了游客上传 在手机端使用的时候需要登陆后台的话则还要手动补全登录后台的网址 如果手机端使用的时候进入首页有一个管理员的入口会比较方便 希望开发者可以考虑😀

**Comment by vastsa** [comment]
等我看看怎么优化一下

**Comment by dianso** [comment]
求这个功能，感谢作者，已star

**Comment by vastsa** [comment]
已新增
