### ISSUE TITLE
Multi-language UI

### ISSUE THREAD

**Issue by Erkak** [vastsa/FileCodeBox#117]
Hi all,
I think it would be great to have option of switching language in UI.
If you implement such feature in future releases I can help with translations to English and Russian languages.

**Comment by vastsa** [comment]
Thank you, At present, English and Chinese will be automatically switched based on the browser language, but there is no manual switching option. I will improve it in the future.
<img width="696" alt="image" src="https://github.com/vastsa/FileCodeBox/assets/48862574/98f371ff-1672-4a1b-97df-44a1a59b8f64">
<img width="833" alt="image" src="https://github.com/vastsa/FileCodeBox/assets/48862574/4f76a546-9097-4f71-8759-35772b88693c">

**Comment by Erkak** [comment]
Thank you,
In addition to this improvement I think another good feature would be possibility for administrator to set default UI language via configuration/environment file.
