### ISSUE TITLE
阿里云EndPointURL配置问题

### ISSUE THREAD

**Issue by linqiu919** [vastsa/FileCodeBox#120]
**version：2.0 Beta**
**deploy：1Panel部署**

![image](https://github.com/vastsa/FileCodeBox/assets/29888564/17cba589-e766-419b-bebf-30dfeff31216)

如何是阿里云OSS的话，这个S3 EndpointUrl应该配置成什么呢？

配置成：`oss-cn-hangzhou.aliyuncs.com` 这个会报错:
```
 File "/usr/local/lib/python3.9/site-packages/aiobotocore/endpoint.py", line 308, in create_endpoint
 raise ValueError("Invalid endpoint: %s" % endpoint_url)
ValueError: Invalid endpoint: oss-cn-hangzhou.aliyuncs.com
```

配置成：`https://oss-cn-hangzhou.aliyuncs.com`也会报错：

```
File "/usr/local/lib/python3.9/site-packages/aiobotocore/client.py", line 371, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (SecondLevelDomainForbidden) when calling the PutObject operation: Please use virtual hosted style to access.
```

还有一个问题，如果在更改S3协议之前，使用本地存储上传的文件，在修改为S3协议后，之前本地上传的文件就无法删除了。
![image](https://github.com/vastsa/FileCodeBox/assets/29888564/654a0258-156e-414f-97b2-c410aa393bb9)

**Comment by 1275788667** [comment]
腾讯cos也有同样的问题 交流群还没加进去  楼主解决了吗

**Comment by chasetumi** [comment]
此处填写Bucket域名，即BucketName.Endpoint。
比如桶：test-bucket，Endpoint：oss-cn-hangzhou.aliyuncs.com，
此处填写完整Bucket域名：https://test-bucket.oss-cn-hangzhou.aliyuncs.com/

**Comment by 1275788667** [comment]
谢谢  测试可以  希望作者能添加自定义存储路径的功能 @chasetumi @veoco

**Comment by 1275788667** [comment]
> 谢谢 测试可以 希望作者能添加自定义存储路径的功能

发现把存储桶名称改了就会传到自定义的目录下了  存储桶名称实际是目录名，，

**Comment by chasetumi** [comment]
对，配置里的S3 Bucket Name就是自定义目录名。

**Comment by 1275788667** [comment]
> 对，配置里的S3 Bucket Name就是自定义目录名。

老哥 还有一个问题 我s3主机名填写cdn域名似乎无效 是不是也有特定的写法

**Comment by 560e** [comment]
哪位大佬发个完整的示例，学习下，谢谢

**Comment by 1275788667** [comment]
> 哪位大佬发个完整的示例，学习下，谢谢

![image](https://github.com/user-attachments/assets/58558ed8-6ad8-40df-b15b-d04d750a83ad)

**Comment by 560e** [comment]
感谢分享，谢谢

**Comment by 560e** [comment]
感谢大佬，有些字段是填的哪些内容？
主要是这几个：
![image](https://github.com/user-attachments/assets/1ea699c2-0b5d-4e44-aa80-aa31539b02ed)
