### ISSUE TITLE
请问可以自定义底部的 FileCodeBox 或 免责声明 字样？

### ISSUE THREAD

**Issue by hack0573** [vastsa/FileCodeBox#121]
公司内部搭建一个类似的文件柜系统，想修改底部的 FileCodeBox 或 免责声明字样，如果可以，请问是在哪个文件中自定义？

**Comment by vastsa** [comment]
后面我在后台加上这个

**Comment by hack0573** [comment]
> 后面我在后台加上这个，目前你可以自己重新build前端

感谢老大回复！build前端不是很懂，无法通过修改某个文件实现是吧？

**Comment by vastsa** [comment]
> > 后面我在后台加上这个，目前你可以自己重新build前端
> 
> 感谢老大回复！build前端不是很懂，无法通过修改某个文件实现是吧？

搜索js文件，也可以实现

**Comment by vastsa** [comment]
后台新增页面说明配置项
