### ISSUE TITLE
后端界面浅色模式附注文字看不清

### ISSUE THREAD

**Issue by robinspt** [vastsa/FileCodeBox#126]
version：2.0 Beta
浅色模式看不清附注文字，深色模式可以
<img width="1277" alt="A1" src="https://github.com/vastsa/FileCodeBox/assets/46096863/dafa3b81-e0b9-4d90-b583-1e89c43a9d15">
<img width="1278" alt="A2" src="https://github.com/vastsa/FileCodeBox/assets/46096863/625b3e39-bac2-4896-8d12-df5d7ecac91d">

**Comment by robinspt** [comment]
还有系统设置的最后两项，都叫“网站名称”

**Comment by robinspt** [comment]
感谢大佬

**Comment by vastsa** [comment]
已解决，久等了
