### ISSUE TITLE
后台登录页面的bug，提示：未授权或授权校验失败

### ISSUE THREAD

**Issue by OuOumm** [vastsa/FileCodeBox#127]
复现页面：https://share.lanol.cn/#/admin

复现方法：第一次登录成功，退出登录后，在进行登录会提示：未授权或授权校验失败

查看控制台提示如下：
![image](https://github.com/vastsa/FileCodeBox/assets/43441064/d21b0173-69c1-43fb-b29d-8969b7dd75a9)

仔细查看报错路径，发现登录接口路径少了/#/

原登录接口：https://share.lanol.cn/#/admin/login

报错登录接口：https://share.lanol.cn/admin/login

包括在您的演示站也有这个bug。

测试浏览器为edge：版本 120.0.2210.144 (正式版本) (64 位)

系统版本为：win11

新编辑：

是因为登陆页面给了个默认密码，登录的时候就直接提示未授权了，所以建议删除这个默认密码，留空处理。

**Comment by vastsa** [comment]
收到，谢谢！

**Comment by vastsa** [comment]
新版已修复

**Comment by ypxun** [comment]
> 新版已修复

奇怪，我用的是docker版本，今天刚升的2.1。之前用的是2.0 beta，可以正常登录admin，反而2.1版本出现了这个issue的问题，f12看了下控制台，报错一模一样。
虽然浏览器地址栏是https://a.a.com/#/admin，但post的反而是https://a.a.com/admin/login

**Comment by assassinliujie** [comment]
> 新版已修复

docker版好像还是有这个bug
