### ISSUE TITLE
分享多条内容会显示历史分享记录，可否高亮最新的分享？

### ISSUE THREAD

**Issue by CyberXfuck** [vastsa/FileCodeBox#129]
遇到问题：用户完成最新的文件分享，弹出历史分享列表，用户只能凭经验找到最新的分享卡片。卡片数量多时会造成困扰。
需求：在最上层单独显示最新完成的分享卡片 or 在列表中高亮显示它。
-----------

遇到问题：当分享次数多，难以根据提取码的区别来联想到对应的文件。
需求：每个卡片加一个简单的数字序号，让用户对每个文件有一个简单记忆点。或者在用户持有的分享卡片上显示文件或文字预览。
-----------

纯需求：加一个保存二维码到相册的按钮。二维码生成时，编号（如有）显示在图片中间。
-----------

一点小想法，谢谢作者。

**Comment by vastsa** [comment]
1. 会的我在使用也发现了，每次都得翻到底部去找。
2. 二维码这个我需要看一下组件怎么使用。
等到3k star我解决一波issues.

**Comment by vastsa** [comment]
二维码已更新，然后新分享的会放到第一个了
