### ISSUE TITLE
Potential Information Leakage

### ISSUE THREAD

**Issue by nevercodecorrect** [vastsa/FileCodeBox#133]
**Describe the bug**
In the settings' `__init__` function, it stores sensitive data including onedrive password, AWS key into a plaintext env file which is a potential security issue described in [CWE-312](https://cwe.mitre.org/data/definitions/312.html).

**To Reproduce**
Run the settings function.

**Expected behavior**
The password should stay in the memory or change the env file permission to only available to the user running the service.

**Comment by vastsa** [comment]
thank you,I will update it

**Comment by vastsa** [comment]
File storage deleted
