### ISSUE TITLE
文件二维码在前端拼接结果好像有错误

### ISSUE THREAD

**Issue by DFP86** [vastsa/FileCodeBox#135]
版本2.0 beta版

描述：
上传文件成功后，页面的二维码是没有错的，扫码点链接可以跳到对应的文件下载页面。
但重新进入页面并输入取件码后，弹出的tab这个文件对应的二维码（对应的link信息）缺少了域名。

举例：
上传成功后页面显示的二维码是： www.aaa.com/share/download?key=xxxx&code=xxxx

重新进入网页输入取件码后，页面的二维码变成了：/share/download?key=xxxx&code=xxxx
↑ 域名丢失了，可能是生成时候有个参数没传过来。

P.S. admin后台页面，文件过期时间显示有点繁琐，目前是
![image](https://github.com/vastsa/FileCodeBox/assets/12046701/91dd8c86-1df3-486b-804c-0065e3e95e50)

不紧急，不影响使用。有空再修复吧！谢谢大佬~~~~

**Comment by vastsa** [comment]
已修复
