### ISSUE TITLE
大文件上传会失败

### ISSUE THREAD

**Issue by mp075496706** [vastsa/FileCodeBox#138]
版本：2.0
设置：已在后台设置文件大小为16106127360

上传一个10G的文件，在上传界面能跑到100%，但是最终会上传失败。
无论是使用S3存储还是本地存储，只要是大文件都会失败。相反几百兆的文件可以上传成功。

**Comment by vastsa** [comment]
https://github.com/vastsa/FileCodeBox?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
设置了吗

**Comment by mp075496706** [comment]
> https://github.com/vastsa/FileCodeBox?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 设置了吗

设置了。
我F12开了一下页面报错的信息，有：
Error handling response: TypeError: Cannot read properties of undefined (reading 'isM3U8Video')
    at chrome-extension://ncennffkjdiamlpmcbajkmaiiiddgioo/js/xl-content.js:1:14139

Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received

**Comment by mp075496706** [comment]
> https://github.com/vastsa/FileCodeBox?tab=readme-ov-file#%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98 设置了吗

文件上传到100%的时候，失败时，有一条报错：
request-aa27c475.js:11 
        
        
       POST https://www.nofun.top:10109/share/file/ 500 (Internal Server Error)
