### ISSUE TITLE
说明页面

### ISSUE THREAD

**Issue by MuskZhouMQ** [vastsa/FileCodeBox#149]
是否可以在输入密码的框内或者旁边加入一个白框用于显示关于界面或者用于说明，大致这样
<img width="1606" alt="image" src="https://github.com/vastsa/FileCodeBox/assets/78646615/6ea84a1a-7b3e-4ecf-bd9b-d605dcac4618">
或者将整体两个白框进行重新布局，让用户可以选择是否开启关于页面的

**Comment by MuskZhouMQ** [comment]
> 需要说明什么内容呢

比如使用方法，上传内容，禁止的内容，还有免责一类的

**Comment by vastsa** [comment]
后台新增页面配置设置项
