### ISSUE TITLE
希望优先更新后台路径自定义功能

### ISSUE THREAD

**Issue by snakeysky** [vastsa/FileCodeBox#156]
使用默认admin路径还是不太安全，如果要把这个放在公网用的话。
另外是否可以考虑，如不允许访客上传开启，则不要再向服务器实际提交或显示那个上传进度条。直接返回一个错误不允许上传即可。

**Comment by vastsa** [comment]
收到

**Comment by vastsa** [comment]
已更新为前端判断是否开启游客上传

**Comment by vastsa** [comment]
后台地址不方便自定义，建议使用nginx操作一下哦
