### ISSUE TITLE
错误的取件码

### ISSUE THREAD

**Issue by pujl** [vastsa/FileCodeBox#157]
为什么我生成了带字母的取件码，然后去取件点击下载也没反应

**Comment by pujl** [comment]
![image](https://github.com/vastsa/FileCodeBox/assets/46348028/5fe20434-e2b4-4890-b5ba-21b1df70ca82)

**Comment by vastsa** [comment]
<img width="1352" alt="image" src="https://github.com/vastsa/FileCodeBox/assets/48862574/417c8dc8-a622-4326-bb75-85b719350ca4">
我这边测试可以下载哦

**Comment by pujl** [comment]
好的，我再试试，不过取件页面不是只有数字吗？怎么生成了带字母的取件码呢？我有点不明白这是bug还是就是这样的？

**Comment by pujl** [comment]
感谢作者的回复，这个软件和好用，我很喜欢，感谢作者的付出
