### ISSUE TITLE
V1.5.6 docker image依然800多MB

### ISSUE THREAD

**Issue by Feiyuyu0503** [vastsa/FileCodeBox#16]
小硬盘有点吃不消...

**Comment by vastsa** [comment]
稍等，我检查一下

**Comment by vastsa** [comment]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/48862574/208228355-3a75806d-4d26-4992-97b5-8dcf818ecabd.png">
重新拉取试一下哦，现在是200mb左右

**Comment by Feiyuyu0503** [comment]
多谢，已解决
