### ISSUE TITLE
一个取件码可以获取多个文件

### ISSUE THREAD

**Issue by Jimmy-Effe** [vastsa/FileCodeBox#160]
**Is your feature request related to a problem? Please describe.**
当我想分享多个文件时，往往需要给获取人多个取件码

**Describe the solution you'd like**
可以在上传页面中添加多个或单个文件上传的选项

**Describe alternatives you've considered**
N/A

**Comment by vastsa** [comment]
感觉修改会比较麻烦，目前是选择文件就上传了，可以考虑打包压缩一下
