### ISSUE TITLE
目前文件上传分享出来的二维码，扫码解析出来的下载地址有误

### ISSUE THREAD

**Issue by coolcoolron** [vastsa/FileCodeBox#163]
用的docker部署的，版本是最新的beta。目前上传后，会显示分享地址的二维码。解码出来的这个二维码格式是：https://部署网站域名+提取码。    而正确的下载地址是：https://部署网站的域名/#/?code=提取码。   还望可做改进，辛苦啦！感谢！

**Comment by vastsa** [comment]
已修复，过两分钟更新一下即可

**Comment by coolcoolron** [comment]
> 已修复，过两分钟更新一下即可

刚更新了docker，目前出来二维码分享下载地址是：https://部署网站的域名/#/提取码   ，我看直接可以下载链接是 https://部署网站的域名/#/?code=提取码  哈哈哈，还辛苦可以看一下

**Comment by vastsa** [comment]
可以啦哈哈哈哈哈
