### ISSUE TITLE
后台管理 文件存活日期

### ISSUE THREAD

**Issue by mobeicanyue** [vastsa/FileCodeBox#167]
**Is your feature request related to a problem? Please describe.**
![1000067120](https://github.com/vastsa/FileCodeBox/assets/81098819/8765368c-ce1f-41fb-ba5e-3be7aaacc4bb)

**Describe the solution you'd like**
我希望后台可以支持管理前端的文件存活日期，因为永久时长太长了
后台管理做成一个可以选择存活日期的形式
**Describe alternatives you've considered**

**Additional context**

**Comment by vastsa** [comment]
后面加到后台配置选项

**Comment by mobeicanyue** [comment]
感谢回复！
要不直接简单点，给 永久时长 加个开关也行。
