### ISSUE TITLE
开启游客上传失效

### ISSUE THREAD

**Issue by telnetpig** [vastsa/FileCodeBox#174]
**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Ubuntu 20.04
 - Browser [e.g. chrome, safari]chrome，firefox
 - Version [e.g. 22]2.1
在后台的系统设置，选开启游客上传，保存，退出登录之后，在不关浏览器的情况下，可以以游客身份上传（似乎是设置得到缓存）。
关闭浏览器，再次上传时，或者以无痕模式上传，浏览器上方提示本站关闭游客上传，寄件箱显示上传失败，试了多次，结果也是这样。
系统设置中的“开启游客上传”似乎没有被保存？

**Comment by vastsa** [comment]
请尝试更新，我测试没问题哦

**Comment by vastsa** [comment]
已修复，请稍后重新更新系统
