### ISSUE TITLE
自动填充错误

### ISSUE THREAD

**Issue by buyfakett** [vastsa/FileCodeBox#176]
扫描二维码后，文件输入框里自动填充的是`uri`，而不是`code`变量

**Comment by vastsa** [comment]
更像版本试一下哦，我这边测试站好像没问题
![image](https://github.com/vastsa/FileCodeBox/assets/48862574/d809afc7-5913-4f75-aefc-4ebf1c7fcab0)

**Comment by buyfakett** [comment]
我使用的是`beta`这个`tag` ，我看是19小时前更新的

**Comment by vastsa** [comment]
那应该就是新版的，我再看一下

**Comment by vastsa** [comment]
具体复现有吗
