### ISSUE TITLE
通过1Panel一键部署，版本为beat,部署后正常访问端口，但是无论文件大小，均无法上传成功

### ISSUE THREAD

**Issue by Youngclub** [vastsa/FileCodeBox#177]
1-----正常访问前端：
![image](https://github.com/vastsa/FileCodeBox/assets/71318318/22ea8a90-9c4d-4601-bceb-523815f702ee)
![image](https://github.com/vastsa/FileCodeBox/assets/71318318/1fa351f1-95ef-4dbc-83d7-b4d56aab7d57)
2-----上传文件，选择txt格式
![image](https://github.com/vastsa/FileCodeBox/assets/71318318/b1b32105-3a2e-4d5f-a74f-b750e1edc608)
3-----上传失败记录
![image](https://github.com/vastsa/FileCodeBox/assets/71318318/f6497be8-3c9c-4161-8005-49c459251493)
4-----后台文件管理界面
![image](https://github.com/vastsa/FileCodeBox/assets/71318318/5e23c4e7-f967-4707-8c36-7988467e3731)
5-----系统日志
![image](https://github.com/vastsa/FileCodeBox/assets/71318318/96e4ce55-a3eb-41e3-a1b9-05b0ffbf9d4c)

**Comment by vastsa** [comment]
后台设置文件大小了吗

**Comment by vastsa** [comment]
已发现问题，晚上修

**Comment by vastsa** [comment]
更新之后再试试
