### ISSUE TITLE
可以更改不使用本机存储而用其他存储比如cos或者网盘吗？

### ISSUE THREAD

**Issue by abcmiao** [vastsa/FileCodeBox#18]
毕竟服务器存储就那么几十G，存个文件，收带宽影响，下载啥的还是挺费劲的

**Comment by vastsa** [comment]
有什么推荐的吗，我可以看一下哦

**Comment by ZHYCarge** [comment]
> 有什么推荐的吗，我可以看一下哦

[阿里云的OSS](https://www.aliyun.com/product/oss)和[腾讯云的COS](https://cloud.tencent.com/product/cos)性价比都还可以

**Comment by vastsa** [comment]
> 

好滴哦，我看下

**Comment by vastsa** [comment]
可以在storage.py新增存储引擎，参照FileSystemStorage完成方法即可
