### ISSUE TITLE
未授权或授权校验失败

### ISSUE THREAD

**Issue by ypxun** [vastsa/FileCodeBox#180]
和 #127 一模一样的问题，但区别在于：我之前一直使用的是docker部署的2.0 beta版本，可以正常登录后台。升级到docker部署的2.1版本后，无法登录admin管理页。

**Comment by vastsa** [comment]
2.1版本不支持env配置了，都恢复默认配置了，密码应该重置了

**Comment by ypxun** [comment]
> 2.1版本不支持env配置了，都恢复默认配置了，密码应该重置了

OK，谢谢
