### ISSUE TITLE
忘记密码怎么办？

### ISSUE THREAD

**Issue by djdjfjfkeocj** [vastsa/FileCodeBox#182]
2.0忘记密码怎么办

**Comment by vastsa** [comment]
2.0的可以看看.env文件/opt/filecodebox目录下找找
2.0升级2.1密码会重置

**Comment by djdjfjfkeocj** [comment]
ok
我直接重新把映射的路径删了重新启动了一下哈哈

**Comment by Marrrrrrrrry** [comment]
好像不行，就没这个目录

![Image](https://github.com/user-attachments/assets/2c6aa2f0-6a22-4480-97cc-5bb5bff555db)
