### ISSUE TITLE
增加检测文件目录，删除空文件夹

### ISSUE THREAD

**Issue by sunnyhmz7010** [vastsa/FileCodeBox#183]
![1720928451884](https://github.com/user-attachments/assets/6c421ddd-1f56-4751-9e23-6eb8de1853f9)
后端删除文件后，程序目录会留下空文件夹，会越来越多，希望能在管理端删除时检测文件夹是否为空，并删除

**Comment by vastsa** [comment]
好的，我记得应该会自动判断空文件夹并删除的，我有空检查下
