### ISSUE TITLE
Docker部署 bast版本 存储改成阿里云OSS有成功的吗？

### ISSUE THREAD

**Issue by 560e** [vastsa/FileCodeBox#185]
有没有大佬配置成功阿里云OSS的，给个案例，感谢

**Comment by vastsa** [comment]
可以把参数都发我邮箱看看

**Comment by 560e** [comment]
> 可以把参数都发我邮箱看看
感谢回复，我是用阿里云OSS，新家了一个测试的存储桶，参数如图
![image](https://github.com/user-attachments/assets/6253af9d-fe0b-414b-9f09-e5685dd6a0f3)
现在问题是我如何填写对应的存储桶
![image](https://github.com/user-attachments/assets/bce10220-61f5-465c-85d2-46b402d82686)

**Comment by 560e** [comment]
已通过看其他大佬的回复找到正确的配置，现在分享
![image](https://github.com/user-attachments/assets/1f958ebd-c03a-4343-b21a-31ee68f3fc3f)
