### ISSUE TITLE
[ BUG ] 上传限制 （频率） 貌似是无效的

### ISSUE THREAD

**Issue by W4ddl3** [vastsa/FileCodeBox#186]
![Screenshot_20240725_103255_Chrome](https://github.com/user-attachments/assets/3fc653fb-aa77-4510-94e6-899d655f553f)

如图我设置为 60 分钟 1 次，但是实测，我在全新浏览器环境（游客）状态下，也是可以无限高频率上传

我改成 1 分钟 1 次 也是，难道这个功能还没做好吗？

**Comment by vastsa** [comment]
我有空测一下

**Comment by vastsa** [comment]
已修复，如还有问题请反馈

**Comment by W4ddl3** [comment]
> 已修复，如还有问题请反馈

根据测试发现：

1. 限制确实能起作用，说几分钟限制几次，就是几次
2. 限制不会恢复正常，比如1分钟限制3次，3次打满后，我等了5分钟，都没法正常上传，一直提示超过限制
3. 限制不能及时更新，比如我后台 开始设置 1分钟10次 后面再改为 1分钟5次 。如果有一个人在我第一次设置时打开 网页 ，我再改为 1分钟5次，他那里照样可以跑 10次 再超限制。（验证是否应该由服务器端判断，而不是网页端判断？）

另外，能否讲一下您是通过什么参数来判断是否超限制呢？
或许对于解决上面的问题有帮助。

**Comment by vastsa** [comment]
取件错误次数

**Comment by vastsa** [comment]
更新限制需要重启服务器

**Comment by W4ddl3** [comment]
> 更新限制需要重启docker

我表述中提到了，我重启过了容器

限制是限制了，报错不让上传了。
致命问题是等再久这个限制都无法解除 ，这是致命 BUG （因为这个限制必须设置，甚至无法不限制）
