### ISSUE TITLE
希望支持cf的r2存储

### ISSUE THREAD

**Issue by hbestm** [vastsa/FileCodeBox#187]
既然大佬都支持AWS的s3了，也希望支持一下CF的R2，他们基本上是兼容的。

**Comment by vastsa** [comment]
自己试试

**Comment by hbestm** [comment]
我刚刚问了AI，在其指导下确实可以用，大佬不妨在下一个版本直接在列表里面明确标出来，毕竟现在还是一个隐藏属性，感谢大佬的及时回复。

**Comment by 3377** [comment]
> 我刚刚问了AI，在其指导下确实可以用，大佬不妨在下一个版本直接在列表里面明确标出来，毕竟现在还是一个隐藏属性，感谢大佬的及时回复。

CF的R2怎弄呀，请指教一下
