### ISSUE TITLE
[ BUG ] 过期方式 删除 天数 后，上传界面 出现 " day " 选项

### ISSUE THREAD

**Issue by W4ddl3** [vastsa/FileCodeBox#189]
![Screenshot_20240727_183434_Via](https://github.com/user-attachments/assets/159c9ffa-8aa2-48ee-a5e0-1c39db3a7f58)

如图所示，不应该出现这个 day 选项

**Comment by vastsa** [comment]
好滴哟

**Comment by vastsa** [comment]
已修复
