### ISSUE TITLE
日志正常但页面空白

### ISSUE THREAD

**Issue by wangjs-cool** [vastsa/FileCodeBox#190]
作者你好，我在Windows下安装python直接运行main.py，页面加载未报错，但是页面是空白。
python版本为3.9.13，已安装requirements.txt里的模块，运行log正常。
![image](https://github.com/user-attachments/assets/490d18f9-a8a4-4e36-99f2-46f48efe2345)
![image](https://github.com/user-attachments/assets/30ee8aea-2dcd-4410-b704-44876cb069ba)
是我遗漏了什么步骤吗，还是说必须使用docker运行。

**Comment by vastsa** [comment]
<img width="1049" alt="image" src="https://github.com/user-attachments/assets/ea47fd9a-3f0a-491f-8b19-122b03b849fd">
python -m uvicorn main:app --reload --port 12345 --host 0.0.0.0 
我这边启动没有问题，试试loclahost

**Comment by wangjs-cool** [comment]
我发现了一个异常
![image](https://github.com/user-attachments/assets/803bd1fd-e3af-43d6-99bf-434e0082cf8c)

**Comment by wangjs-cool** [comment]
我发现了一个异常：Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.
![image](https://github.com/user-attachments/assets/55524ab9-4447-4606-a8c8-19102755fbca)

**Comment by wangjs-cool** [comment]
我之前在Linux下运行正常，这次是在Windows下运行发现页面空白，是否是js兼容性问题。

**Comment by vastsa** [comment]
应该不至于，和系统应该没关系

**Comment by wangjs-cool** [comment]
我查到了一些资料，但是看不太懂，作者可以看一下吗

**Comment by wangjs-cool** [comment]
我查到了一些资料，但是看不太懂，作者可以看一下吗
https://github.com/869413421/chatgpt-web/issues/40
https://stackoverflow.com/questions/59908927/failed-to-load-module-script-the-server-responded-with-a-non-javascript-mime-ty

**Comment by wangjs-cool** [comment]
我按照下面网站的方法修改了注册表，解决了此问题
https://caddy.community/t/failed-to-load-module-script/17408
我的默认.js为text/plain，修改为了text/javascript
![image](https://github.com/user-attachments/assets/0903863d-b318-43fb-9c95-1cb35d8b373f)

**Comment by vastsa** [comment]
> 我按照下面网站的方法修改了注册表，解决了此问题 https://caddy.community/t/failed-to-load-module-script/17408 我的默认.js为text/plain，修改为了text/javascript ![image](https://private-user-images.githubusercontent.com/56024098/352837931-0903863d-b318-43fb-9c95-1cb35d8b373f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIyNjQ4NDUsIm5iZiI6MTcyMjI2NDU0NSwicGF0aCI6Ii81NjAyNDA5OC8zNTI4Mzc5MzEtMDkwMzg2M2QtYjMxOC00M2ZiLTljOTUtMWNiMzVkOGIzNzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI5VDE0NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4ZTgyMzM5N2RkMGU5MGRmNmQ2NzM3YzFkZTYwNDk3ZTFhM2E4MDBiMjgxOTFmOWM4ZGY2NzU2OTNlMzA0OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OMkfs1mYmXZn7K8HPpMHPkyvfFqmS3KbTZa-JY-Yc_M)

👌
