### ISSUE TITLE
Docker部署 bast版本 存储改成阿里云，上传后文件名会变成随机码

### ISSUE THREAD

**Issue by 560e** [vastsa/FileCodeBox#192]
已经成功将存储改成阿里云OSS，但是发现上传到OSS的文件会变成随机文件名，请问如何保持原来的文件名
这是上传到OSS的文件
![image](https://github.com/user-attachments/assets/6655ac9c-5083-47c7-a794-4f77f2130f1e)

**Comment by vastsa** [comment]
防止文件覆盖，如有需要需自行修改代码逻辑
