### ISSUE TITLE
100mb的文件上传失败显示文件过大

### ISSUE THREAD

**Issue by Andersonong-github** [vastsa/FileCodeBox#195]
**Describe the bug**
你好，首先谢谢你们的软件，我开始试着用，已经调整了我的传送文件大小为5G，但是就100多mb的文件也发不出去，然后出现错误的文字写着文件过大？可以帮帮忙看看是否有什么错误吗？

![image](https://github.com/user-attachments/assets/d82f6e16-8711-404e-b07a-f1c2516efb0d)

**Comment by vastsa** [comment]
https://github.com/vastsa/FileCodeBox/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#413-request-entity-too-large
这个尝试了吗

**Comment by Andersonong-github** [comment]
谢谢答复，我找不到我的nginx.conf配置文件。我是经由1Panel的应用商店一键部署的。。就找到一些的这些
![image](https://github.com/user-attachments/assets/eb6fa575-a3ed-4a93-aca4-bd99d626c247)
![image](https://github.com/user-attachments/assets/287ad74f-7621-44e7-a128-ba75017ef254)

**Comment by vastsa** [comment]
请问有使用反代吗

**Comment by Andersonong-github** [comment]
你好，我修改了，然后重启了container..

![image](https://github.com/user-attachments/assets/bea45049-990a-4bcc-a718-41d976e7106d)
![image](https://github.com/user-attachments/assets/918d830f-d96a-42c0-bf76-50408e7fbcd7)
还是一样的问题呢。。。

**Comment by yuju520** [comment]
有可能是因为开了CF的CDN的原因，有100MB上传限制

**Comment by carolcoral** [comment]
修改上传文件大小限制后必须重启容器

**Comment by Worthing667** [comment]
![配置修改](https://github.com/user-attachments/assets/c0ebad23-e850-4cc6-86a3-0a537ebf792b)
在左边菜单找到`网站`，选择`设置`→`性能调整`，就能看到`client_max_body_size`

**Comment by carolcoral** [comment]
1p服务只需要在网站-文件夹，找到`../proxy/root.conf` 文件打开，粘贴下面的代码进去，然后重启openresty即可
```shell
client_max_body_size 10g;
```

<img width="1160" alt="image" src="https://github.com/user-attachments/assets/de473e51-59bd-42c1-afc1-46be57084aef">

**Comment by Chenime233** [comment]
> 有可能是因为开了CF的CDN的原因，有100MB上传限制

原来如此

**Comment by felixnie** [comment]
In case you are using Nginx Proxy Manager: https://github.com/NginxProxyManager/nginx-proxy-manager/issues/93#issuecomment-485040136
