### ISSUE TITLE
如何修改端口

### ISSUE THREAD

**Issue by telnetpig** [vastsa/FileCodeBox#203]
docker run -d --restart=always -p 12345:12345 -v /opt/FileCodeBox/:/app/data --name filecodebox lanol/filecodebox:latest
冒号前后的两个12345都表示访问端口吗？
如果要修改为通过6000端口访问，是否是修改为-p 6000:6000

**Comment by u1s3-fu** [comment]
只修改前面的端口号即可，一个是容器端口一个是本机端口。这样 -p 6000:12345
