### ISSUE TITLE
移动端界面希望可以优化

### ISSUE THREAD

**Issue by FreeRolled** [vastsa/FileCodeBox#207]
因为是文件中转站，大部分是pc和移动端文件相互中转/分享。
1：左上角三个功能按钮（移动端界面太小），希望可以重新设计大一点，方便移动端触控。
2：界面既然采用9数字键输入，希望增加一个删除按键，更加符合移动端。

**Comment by vastsa** [comment]
新版静态预览：https://fcb.065065.xyz/
