### ISSUE TITLE
取件码带字母，但是取件的时候只能输数字

### ISSUE THREAD

**Issue by gufeng0** [vastsa/FileCodeBox#213]
我看有人提到过这个问题，但是没有回复就直接关闭了

**Comment by vastsa** [comment]
可以用键盘输入，新版本ui会取消页面上的键盘

**Comment by gufeng0** [comment]
> 可以用键盘输入，新版本ui会取消页面上的键盘

okok,项目很不错，提一两点小建议
1. 文件管理列表的取件码可以一键点击复制到剪切板
2. 上传文件的时候可以添加备注说明

**Comment by vastsa** [comment]
> > 可以用键盘输入，新版本ui会取消页面上的键盘
> 
> okok,项目很不错，提一两点小建议
> 
> 1. 文件管理列表的取件码可以一键点击复制到剪切板
> 2. 上传文件的时候可以添加备注说明

get
