### ISSUE TITLE
管理后台输入任意密码都可以登录成功

### ISSUE THREAD

**Issue by dylan8888** [vastsa/FileCodeBox#218]
用的是docker部署，当前latest版。管理后台/#/admin，输入任意密码都可以登录成功。在管理后台修改密码无任何效果。

**Comment by vastsa** [comment]
稍等我看看

**Comment by dylan8888** [comment]
您好，您的邮件我已经收到，我会尽快阅读和回复，谢谢您的邮件。

**Comment by vastsa** [comment]
确实存在，等待我更新

**Comment by dylan8888** [comment]
感谢感谢。非常实用的工具，差点就放弃了。

**Comment by vastsa** [comment]
> 感谢感谢。非常实用的工具，差点就放弃了。

哈哈哈哈不好意思，昨天更新了一波导致的问题，请使用 beta 版本
