### ISSUE TITLE
主线上传bug

### ISSUE THREAD

**Issue by wangjs-cool** [vastsa/FileCodeBox#22]
我clone了主线最新程序，运行后发现提示上传功能已关闭，.env也配置了，经测试，发现checkFile函数在判断是否允许上传时写的是`if (!this.enable)`，但是我在其他地方再没找到过this.enable这个变量，只找到了this.enableUpload这个变量，将此处修复后，可以上传文件。
上面bug修复后发现只能上传文件，不能上传文本。对比了一下release版本，发现checkFile函数是新增加的，release版本中并没有。问题应该出在checkFile函数默认传入的是文件了，在判断`if (file.size > this.fileSizeLimit)`时应该出错了，当file是文本时，应该没有.size的属性。自己尝试修改了一下，在判断size之前，加了` if (Object.prototype.toString.call(file) == '[object File]')`，现在可以上传文本了。
本人不太熟悉Vue，如有说错，请见谅。

**Comment by vastsa** [comment]
收到，我检查一下，之前有反馈说最好在上传之前做检查，不然也会消耗服务器流量，然后后面加了一下，我更新一下

**Comment by vastsa** [comment]
已经修复啦，可以clone最新代码看下
