### ISSUE TITLE
在后台修改网站名称和网站描述实际不会变

### ISSUE THREAD

**Issue by Suteinua** [vastsa/FileCodeBox#229]
但通知标题和通知内容会变
目前有办法解决吗？

希望可以自定义每个地方的文本

另：选择到2023主题虽然网站名称会改变，但会造成所有页面都全白不显示的bug

**Comment by vastsa** [comment]
更换主题需要重启，后面完善自定义

**Comment by JlonGit** [comment]
重启之后还是有全白什么也不显示的bug，貌似管理页面修改上传大小限制无效

**Comment by sbtime** [comment]
unsubscribe



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Jlon ***@***.***&gt;
发送时间: 2024年12月12日 16:07
收件人: vastsa/FileCodeBox ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [vastsa/FileCodeBox] 在后台修改网站名称和网站描述实际不会变 (Issue #229)





 
重启之后还是有全白什么也不显示的bug，貌似管理页面修改上传大小限制无效

**Comment by vastsa** [comment]
> 重启之后还是有全白什么也不显示的bug，貌似管理页面修改上传大小限制无效

已修复
