### ISSUE TITLE
使用2023版本主题不能正常接收文本类的快件

### ISSUE THREAD

**Issue by endgeofendlessworld** [vastsa/FileCodeBox#234]
发帖时是docker版最新的beta版本，收取文本形式的快件时只有点击下载选项，点击后发送的内容只会出现在网页的访问路径，网页会显示notfound。重新为老版本UI做一个专门处理文本的前端可能比较麻烦，但可以直接将文本显示在网页不用任何css上，用户可以直接复制。

https://github.com/user-attachments/assets/802cdfd3-5340-4cac-9524-70d9cfc3a300

**Comment by vastsa** [comment]
谢谢，这个应该是改版的时候影响到了，我修复一下

**Comment by vastsa** [comment]
fix:https://github.com/vastsa/FileCodeBox/commit/3592db09abffb152380276a154de8322cf372109

**Comment by endgeofendlessworld** [comment]
好的，感谢大佬
