### ISSUE TITLE
取件提示{"detail":"Not Found"}

### ISSUE THREAD

**Issue by Mabisi** [vastsa/FileCodeBox#24]
![image](https://user-images.githubusercontent.com/19968269/209668455-0e3045e7-1875-497e-be2a-5f2cb0d2f355.png)

**Comment by wangjs-cool** [comment]
我也发现了这个问题，#23里有描述。

**Comment by Mabisi** [comment]
> 请问是哪个版本以及取件码过期方式是什么呢

哪里可以看到版本呢？
看docker是5天前的包
lanol/filecodebox               arm         fe21ae6314a9   5 days ago      152MB
看日志只有这一段错误
![(20221227)21 41 38](https://user-images.githubusercontent.com/19968269/209675189-d58fa582-a522-4e3a-9d59-35eb9d1ac5a9.png)

**Comment by vastsa** [comment]
嗯嗯好滴麻烦了，我检查一下

**Comment by dev-lake** [comment]
直接后台下载会出现这个问题

**Comment by vastsa** [comment]
后台下载是会这样的，防止后台下载占用下载次数，所以后台那边是真实存储地址
