### ISSUE TITLE
希望增加直接把服务器内文件添加到下载目录的功能，而不需要从页面上传

### ISSUE THREAD

**Issue by dev-lake** [vastsa/FileCodeBox#25]

**Comment by vastsa** [comment]
可以详细说一下嘛，应用场景，使用方式啥的，这样的话岂不是游客也可以获取到服务器文件了

**Comment by dev-lake** [comment]
> 可以详细说一下嘛，应用场景，使用方式啥的，这样的话岂不是游客也可以获取到服务器文件了

比如服务器上有一个大文件需要提供给客户下载，我直接把文件移动到相应目录可以直接提供下载（或者用命令行工具指定下路径，自动复制过去也行，把路径加到数据库也行）。表达的不是很清楚，不知道您能不能明白我的意思。

**Comment by vastsa** [comment]
懂了，可以考虑在后台加一个目录list

**Comment by vastsa** [comment]
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/48862574/212654056-ea223995-3f90-4557-b273-0917ccf8f81e.png">
简单的加了一下，需要将文件移动至/data/files里面

**Comment by dev-lake** [comment]
感谢付出

**Comment by yyxx1997** [comment]
这是什么功能，我怎么在后台找不到啊。
