### ISSUE TITLE
自定义了banner后，上传功能就关闭了

### ISSUE THREAD

**Issue by tinyxingqiu** [vastsa/FileCodeBox#26]
![image](https://user-images.githubusercontent.com/50978550/209773661-2a293975-77d1-4e91-9036-7d802d4bda9e.png)

**Comment by tinyxingqiu** [comment]
是docker最新版

**Comment by tinyxingqiu** [comment]
![image](https://user-images.githubusercontent.com/50978550/209774091-7dbd3f63-a076-4a41-935c-b9a64ce6a42a.png)

**Comment by vastsa** [comment]
嗯嗯收到，我检查一下，谢谢提出问题

**Comment by MerudaArashi** [comment]
1.5.9好像也没解决

**Comment by vastsa** [comment]
已修复，等我发板

**Comment by MerudaArashi** [comment]
可以了，谢谢大佬。
