### ISSUE TITLE
安全问题！

### ISSUE THREAD

**Issue by tinyxingqiu** [vastsa/FileCodeBox#27]
部署成功后，不做任何配置的情况下，默认管理员密码是admin，这十分危险。请作者考虑改为：第一次部署成功时，随机生成复杂密码。

**Comment by vastsa** [comment]
了解，谢谢提醒

**Comment by vastsa** [comment]
<img width="464" alt="image" src="https://user-images.githubusercontent.com/48862574/212616600-2b2e1f5c-f114-4eaf-adab-193577d0dda6.png">
新版本已接近
