### ISSUE TITLE
【Bug】分享文本的时候回自动删掉换行和回车

### ISSUE THREAD

**Issue by Hansi7** [vastsa/FileCodeBox#32]
存入文本时候比如输入1【回车】2【回车】3【回车】，然后存入。
取件的时候输入码可以看到内容【冒号】，后面是1 2 3。感觉是有不可见字符的。
但是点击鼠标，显示复制成功后。粘贴到记事本里实际是”123“三个连续的数字。
比如我分享多个网址，用回车分割后存入。收到的数据里面就不是很方便。

**Comment by vastsa** [comment]
目前是文本框，不支持换行正常，但是的确不方便，我支持下markdown吧

**Comment by vastsa** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/48862574/212661594-4a0f30de-4848-42dc-93cd-3bda41c86795.png">
已解决，暂时还是先显示换行吧
