### ISSUE TITLE
docker部署不支持纯ipv6访问吗？

### ISSUE THREAD

**Issue by LeonX86** [vastsa/FileCodeBox#33]
如题（docker仅host支持ipv6，我的mc服务器和ddns-go ipv6公网访问均正常）
![image](https://user-images.githubusercontent.com/49100008/210170555-746b7a5f-bd0f-44d7-a724-744e92341509.png)

**Comment by vastsa** [comment]
这个可能要看docker怎么配置

**Comment by LeonX86** [comment]
看这个手册好像是不支持ipv4和ipv6同时监听https://www.uvicorn.org/settings/#socket-binding
😂😂

**Comment by LeonX86** [comment]
> 这个可能要看docker怎么配置，试试修改main.py最后一行

看这个手册好像是不支持ipv4和ipv6同时监听https://www.uvicorn.org/settings/#socket-binding
😂😂

**Comment by mrwoowoo** [comment]
建议反向代理
