### ISSUE TITLE
feature request:希望admin界面能修改基础的参数

### ISSUE THREAD

**Issue by ReddotCleaner** [vastsa/FileCodeBox#35]
如题，现在admin界面除了查看文件，只剩下设置banner的功能（而且我设置了banner之后好像没看到哪个界面有明显的变化），希望后续能把
```
# 错误次数
ERROR_COUNT=5
# 错误限制分钟数
ERROR_MINUTE=10
# 上传次数
UPLOAD_COUNT=60
# 上传限制分钟数
UPLOAD_MINUTE=1
# 删除过期文件的间隔（分钟）
DELETE_EXPIRE_FILES_INTERVAL=10
# 管理地址
ADMIN_ADDRESS=admin
# 管理密码
ADMIN_PASSWORD=admin
# 文件大小限制，默认10MB
FILE_SIZE_LIMIT=10
```
这些基础的参数设置加入到管理界面。
另外，中文版readme的 ```FileCoxBox``` --> ```FileCodeBox```  是不是拼写错误了?😑

**Comment by vastsa** [comment]
hhh,谢谢提醒，readme以及改正，有打算将基础设置放到后台哦

**Comment by vastsa** [comment]
banner是这个地方的图片哦
<img width="442" alt="image" src="https://user-images.githubusercontent.com/48862574/211260843-bf3e5685-8331-49c1-92f7-6e73ae15e0f1.png">

**Comment by vastsa** [comment]
新版本将加入
<img width="1358" alt="image" src="https://user-images.githubusercontent.com/48862574/212637248-c7c2b6fd-e5f2-4ae4-9667-e62019f3d2b0.png">
