### ISSUE TITLE
希望首页可以添加一个版本号😂

### ISSUE THREAD

**Issue by Mydong** [vastsa/FileCodeBox#36]
首页的信息可以添加一个版本号，这样就知道要不要更新了；哈哈😂

现在隔断时间就看看有没有更新，时间长了，忘记自己用的是哪个版本了；

![image](https://user-images.githubusercontent.com/14023137/211285464-76ed754e-c2f2-4514-96af-0f6ffc78c3ea.png)

**Comment by vastsa** [comment]
哈哈哈，我在html源码里面加了，不过有时候也忘了更新，我在外面加一个吧
<img width="968" alt="image" src="https://user-images.githubusercontent.com/48862574/211340123-fb8cb1ed-6610-4602-8b85-ccc89b57718e.png">

**Comment by lilisore** [comment]
请问这个页面的版本号，是否可以开放自定义功能。

用您的开源系统搭建了一个中转站给朋友们用，也推广给他们自己搭建，大家反应希望可以支持下自定义，看作者是否有打算。

期待您的回复。
