### ISSUE TITLE
首页的docker是不是还没有更新呀

### ISSUE THREAD

**Issue by Mydong** [vastsa/FileCodeBox#41]
docker部署了，拉取后发现还是原来的，好像没有什么变化呢，是需要自己打包嘛

**Comment by Mydong** [comment]
奇怪全部删除重装了，看日志还是老版本的
![image](https://user-images.githubusercontent.com/14023137/213535433-c83a239b-9486-4bf4-91a3-dcf54ab2c54b.png)

**Comment by vastsa** [comment]
哈哈哈，应该是的，之前的image没删除
