### ISSUE TITLE
更改env值不能生效

### ISSUE THREAD

**Issue by smmya** [vastsa/FileCodeBox#43]
ubuntu20.04
docker 最新
拉取的最新镜像
修改env值的
FILE_SIZE_LIMIT=512
ADMIN_PASSWORD=
不能生效，
但ADMIN_ADDRESS= 
可生效

**Comment by vastsa** [comment]
最新版的话在后台更改试试哦

**Comment by smmya** [comment]
> 最新版的话在后台更改试试哦

成功了，谢谢
