### ISSUE TITLE
能否兼容标准S3协议？

### ISSUE THREAD

**Issue by Tslmuun** [vastsa/FileCodeBox#44]
你好：

很有趣的项目，以后能否兼容标准的S3协议？比如可以使用亚马逊S3，cloudflare R2之类做后端存储。
这样会方便很多。

谢谢你。

**Comment by vastsa** [comment]
允许的，在storage里面可以扩展，根据本地存储，实现方法即可，后面我将注释写一下

**Comment by Tslmuun** [comment]
感谢回复。
