### ISSUE TITLE
.env中修改PORT无效

### ISSUE THREAD

**Issue by wangjs-cool** [vastsa/FileCodeBox#45]
.env中修改PORT无效，后台界面无此设置项，修改了database.db中的值才生效

**Comment by vastsa** [comment]
收到，我修改一下，添加到后台

**Comment by vastsa** [comment]
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/48862574/215768311-c21ba28e-94e3-4965-9c80-c5bcd2a3732e.png">
已新增
