### ISSUE TITLE
是否可以支持大文件上传

### ISSUE THREAD

**Issue by wangjs-cool** [vastsa/FileCodeBox#46]
目前不支持大文件上传，是否考虑支持一下。

**Comment by vastsa** [comment]
收到，谢谢支持，我这边研究一下

**Comment by mrwoowoo** [comment]
可以考虑下分片上传

**Comment by Oldming1** [comment]
大文件上传好像是没有问题，感觉如果经过反代就会出现问题，域名反代只要超过1G文件有概率到最后卡住，ip加端口直接上传2g文件是可以。是否可以针对反代进行一些优化，谢谢

**Comment by vastsa** [comment]
> 大文件上传好像是没有问题，感觉如果经过反代就会出现问题，域名反代只要超过1G文件有概率到最后卡住，ip加端口直接上传2g文件是可以。是否可以针对反代进行一些优化，谢谢

正解，目前正确考虑楼上说的分片上传。反代之后需要在反代配置设置允许上传大小

**Comment by Oldming1** [comment]
> 

反代配置允许上传大小设置了，但是上传到100%一会后会直接消失，整个上传任务就没了，目前还不清楚是什么原因

**Comment by wangjs-cool** [comment]
我觉得不是反代的问题，我这边只是经过了两层域名解析和一个端口映射，大文件就不行了。

**Comment by vastsa** [comment]
开发版本已加入分片，优化后上线

**Comment by vastsa** [comment]
1.7Beta已接入
