### ISSUE TITLE
宝塔面板升级以后，项目运行报错

### ISSUE THREAD

**Issue by uu-xixi** [vastsa/FileCodeBox#50]
宝塔面板升级到最新版：7.9.8 后，原有项目运行报错。无论是使用最新代码还是将python环境升级或降级均无法解决。

Traceback (most recent call last):
  File "/developer/app/FileBox/FileCodeBox-1.6/main.py", line 40, in <module>
    app.mount('/static', StaticFiles(directory='./static'), name="static")
  File "/developer/app/FileBox/FileCodeBox-1.6/ec8939ef06298640a91a4ae82aaefe3d_venv/lib/python3.9/site-packages/starlette/staticfiles.py", line 55, in __init__
    raise RuntimeError(f"Directory '{directory}' does not exist")
RuntimeError: Directory './static' does not exist

**Comment by vastsa** [comment]
这个问题与 #49 相同，均因为Python项目管理器，将项目启动目录设置为系统根目录/，导致找不到文件夹

**Comment by uu-xixi** [comment]
> 这个问题与 #49 相同，均因为Python项目管理器，将项目启动目录设置为系统根目录/，导致找不到文件夹

请问一下，作者最近有升级计划么？

**Comment by vastsa** [comment]
有的，之前有点事情，没时间更新，这段时间之后应该会重构代码，然后完善一下文档，可自定义存储

**Comment by uu-xixi** [comment]
> 
十分感谢

**Comment by uu-xixi** [comment]
> 有的，之前有点事情，没时间更新，这段时间之后应该会重构代码，然后完善一下文档，可自定义存储

十分感谢

**Comment by tyhguan** [comment]
> 这个问题与 #49 相同，均因为Python项目管理器，将项目启动目录设置为系统根目录/，导致找不到文件夹

所以，请问这个情况要怎么解决？

**Comment by uu-xixi** [comment]
> > 这个问题与 #49 相同，均因为Python项目管理器，将项目启动目录设置为系统根目录/，导致找不到文件夹
> 
> 所以，请问这个情况要怎么解决？

降级宝塔面板版本or等待作者修复

**Comment by tyhguan** [comment]
> > > 这个问题与 #49 相同，均因为Python项目管理器，将项目启动目录设置为系统根目录/，导致找不到文件夹
> > 
> > 
> > 所以，请问这个情况要怎么解决？
> 
> 降级宝塔面板版本or等待作者修复

降级宝塔版本？要降到哪个版本？我现在是7.9.82 测试版

**Comment by uu-xixi** [comment]
> 

不建议回退版本，官方不建议回退版本，也不支持该功能。按照网上说的方法进行回退有未知风险，我现在坐等作者修复了。

**Comment by uu-xixi** [comment]
> > > > 这个问题与 #49 相同，均因为Python项目管理器，将项目启动目录设置为系统根目录/，导致找不到文件夹
> > > 
> > > 
> > > 所以，请问这个情况要怎么解决？
> > 
> > 
> > 降级宝塔面板版本or等待作者修复
> 
> 降级宝塔版本？要降到哪个版本？我现在是7.9.82 测试版


我不建议回退版本，官方也不建议回退版本，也不支持回退功能。按照网上说的方法进行回退有未知风险，我现在坐等作者修复了。

**Comment by vastsa** [comment]
好滴，下个版本将加入分片上传，尝试修复宝塔

**Comment by vastsa** [comment]
问题已解决，安装python项目管理器2.0即可
https://www.yuque.com/lxyo/work/lc1oe0xqk8t9b976?singleDoc# 《文件快递柜项目说明》

**Comment by tyhguan** [comment]
> 问题已解决，安装python项目管理器2.0即可 https://www.yuque.com/lxyo/work/lc1oe0xqk8t9b976?singleDoc# 《文件快递柜项目说明》

按照教程跑的，请问安装后500错误应该排查哪里？ex.rui.ink
