### ISSUE TITLE
后台管理地址怎么登录

### ISSUE THREAD

**Issue by alimalls** [vastsa/FileCodeBox#51]
后台管理地址怎么登录，我是默认的docker部署的，看文件env配置，管理地址和密码是一串数字。

**Comment by vastsa** [comment]
env里面有一个admin_address:
这个是后台路径
所以就是->http://域名/{admin_address}
密码就是admin_password

**Comment by alimalls** [comment]
好的，谢谢。

**Comment by aceslup** [comment]
看样子必须创建.env文件

**Comment by aceslup** [comment]
> 看样子必须创建.env文件

初始化了一个.env，找到了
