### ISSUE TITLE
arm平台docker镜像搭建。

### ISSUE THREAD

**Issue by waifei01** [vastsa/FileCodeBox#60]
请问是否可以同步创建arm平台的docker镜像呢？

**Comment by vastsa** [comment]
有的哦：
docker run -d --restart=always -p 12345:12345 -v /opt/FileCodeBox/:/app/data --name filecodebox lanol/filecodebox:arm

**Comment by waifei01** [comment]
嗯，看见里面显示的是arm64，以为不能使用，试着docker build也是安装失败，谢谢提醒。

> 有的哦： docker run -d --restart=always -p 12345:12345 -v /opt/FileCodeBox/:/app/data --name filecodebox lanol/filecodebox:arm

**Comment by vastsa** [comment]
收到，等后面我看下怎么用Github Actions自动发布

**Comment by waifei01** [comment]
> 收到，等后面我看下怎么用Github Actions自动发布

谢谢，费心了。

**Comment by wxydejoy** [comment]
需要 armv7  +1 
感谢大佬

**Comment by hellodk34** [comment]
armv8 使用正常。

```
lscpu
Architecture:          aarch64
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    4
Socket(s):             1
Model:                 4
Model name:            ARMv8 Processor rev 4 (v8l)
CPU max MHz:           1512.0000
CPU min MHz:           100.0000
BogoMIPS:              48.00
L1d cache:             unknown size
L1i cache:             unknown size
L2 cache:              unknown size
Flags:                 fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
```

`docker run -d --restart=always -p 12345:12345 -v /mnt/ssd32/FileCodeBox/:/app/data --name filecodebox lanol/filecodebox:arm`

**Comment by vastsa** [comment]
已同步搭建
