### ISSUE TITLE
创建失败怎么破？

### ISSUE THREAD

**Issue by tyhguan** [vastsa/FileCodeBox#62]
按照https://www.yuque.com/lxyo/work/lc1oe0xqk8t9b976 这个教程来的，但就是创建失败。

![QQ截图20230323115653](https://user-images.githubusercontent.com/38853851/227099116-60b87dce-5a93-4eab-81ed-3202681296d9.png)
![QQ截图20230323115630](https://user-images.githubusercontent.com/38853851/227099118-6d8af349-7097-473f-9549-5484a35d5e62.png)
![QQ截图20230323115647](https://user-images.githubusercontent.com/38853851/227099126-22bd929e-7ca1-4361-befc-e567f46b65f8.png)

**Comment by vastsa** [comment]
目前应该是没有勾选安装requirements.txt
