### ISSUE TITLE
1.7版没法密码？默认的含字母

### ISSUE THREAD

**Issue by a2313153** [vastsa/FileCodeBox#63]
后台看有存储引擎，以后会支持oss或挂载网盘？
也希望可以自定义提取码长度、类型（字母或数字或混合）

**Comment by a2313153** [comment]
分享文件管理里建议能增加修改功能
开启上传功能可以支持仅登录后台后管理员上传和游客上传2种

**Comment by vastsa** [comment]
会支持挂载
你直接关闭就只能管理员登录上传了

**Comment by vastsa** [comment]
已支持s3
