### ISSUE TITLE
docker Log 中没有默认密码  修改.env 会被还原

### ISSUE THREAD

**Issue by wzydale** [vastsa/FileCodeBox#65]
![image](https://user-images.githubusercontent.com/32425043/229163913-cc6f6704-ef41-4fd9-84f3-8486000e7291.png)
docker Log 中没有默认密码怎么办，修改.env之后 一重启docker就会被改回修改前的状态

**Comment by vastsa** [comment]
删除/opt/FileCodeBox里面的.env
然后重启

**Comment by vastsa** [comment]
使用2.0beta版本
