### ISSUE TITLE
功能请求

### ISSUE THREAD

**Issue by IceBingQI** [vastsa/FileCodeBox#66]
1.希望支持在后台自定义文件的存放位置。
2.储存方式可以添加FTP,SMB,WEBDEV 等。
3.给上传入口添加密码设置，或可以设置为仅管理员可上传（是可以让用户在后台管理中选择的，不是默认添加上传限制）

**Comment by vastsa** [comment]
1，2收到
第三点现在管理员关闭上传之后，只有登录后台才可以上传
