### ISSUE TITLE
建议新增OneDrive存储

### ISSUE THREAD

**Issue by xiaoxin3242** [vastsa/FileCodeBox#71]
本机存储和带宽有限，阿里云OSS太贵了，OneDrive正适合做这种临时存储

**Comment by vastsa** [comment]
收到

**Comment by Do1e** [comment]
@vastsa 存储在本地的文件可以通过FileResponse的参数指定下载的名称，新增OneDrive存储的话要如何保证下载的文件名不是uuid_file_name呢？

**Comment by vastsa** [comment]
> @vastsa 存储在本地的文件可以通过FileResponse的参数指定下载的名称，新增OneDrive存储的话要如何保证下载的文件名不是uuid_file_name呢？

或许可以考虑文件还是以原名称上传，但是路径可以加一个uuid，只要确保文件不被覆盖即可
