### ISSUE TITLE
可以做对S3对象存储协议兼容吗？

### ISSUE THREAD

**Issue by Oldming1** [vastsa/FileCodeBox#74]
希望能对接minio 兼容s3接口，应该是和oss类似，是否可以使用oss对接minio？希望能做一点S3兼容就可以更多存储对接了

**Comment by lilisore** [comment]
minio同求

**Comment by vastsa** [comment]
收到，等我这边闲下来就进行更新

**Comment by vastsa** [comment]
已兼容
<img width="1140" alt="image" src="https://github.com/vastsa/FileCodeBox/assets/48862574/a6f12b19-1702-46a9-a276-4acd59109155">
