### ISSUE TITLE
请问页面底部的版本号，是否可以开放自定义功能。

### ISSUE THREAD

**Issue by lilisore** [vastsa/FileCodeBox#75]
请问页面底部的版本号，是否可以开放自定义功能。在.env和页面上都没有看到可以修改的地方。

用您的开源系统搭建了一个中转站给朋友们用，也推广给他们自己搭建，大家反应希望可以支持下自定义，看作者是否有打算。

期待您的回复。

_Originally posted by @lilisore in https://github.com/vastsa/FileCodeBox/issues/36#issuecomment-1625718029_

**Comment by vastsa** [comment]
版本号可以自定义，只需要留个地方保留出处即可，可以使用display:none

**Comment by lilisore** [comment]
按照您说的display:none，加入.env里面，停止容器或者删除容器后，再启动docker容器，.env文件display:none这段代码自动消失，不知道是否为我配置的问题，还请指教。

最下角的中间位置，依然存在。

[FileCodeBox V1.6 Beta](https://github.com/vastsa/FileCodeBox)

**Comment by vastsa** [comment]
删除容器后会自动用docker的覆盖，你可以自己打包
