### ISSUE TITLE
手动构建docker镜像并创建容器，前端可以正常使用，但是后台界面异常

### ISSUE THREAD

**Issue by nixingshiguang** [vastsa/FileCodeBox#79]
<img width="1239" alt="微信截图_20230808225647" src="https://github.com/vastsa/FileCodeBox/assets/94590099/dd754594-3fce-4517-8a64-535ebd812f2f">
# 手动构建docker镜像并创建容器，前端可以正常使用，但是后台界面异常
## 环境
+ 系统：Ubuntu22.04
+ 面板：1-panel

**Comment by vastsa** [comment]
好像是后端报错了，等我重构一下

**Comment by vastsa** [comment]
建议使用1.6的代码，目前latest的有问题

**Comment by nixingshiguang** [comment]
> 建议使用1.6的代码，目前latest的有问题

使用1.6的版本成功，谢谢指点！

顺便提个小建议：登录后台页面的密码输入框建议换成password类型

**Comment by vastsa** [comment]
> 

好滴
