### ISSUE TITLE
文本分享增强

### ISSUE THREAD

**Issue by wxyShine** [vastsa/FileCodeBox#89]
是否可以增加代码片段或者日志文本  高亮～

**Comment by vastsa** [comment]
在考虑文本输入加入富文本

**Comment by vastsa** [comment]
![b808baa3e6cb8a76e16e3de4e04988e0](https://github.com/vastsa/FileCodeBox/assets/48862574/4cf580ca-338d-4fd6-b27a-925cf98fb6b3)
已支持mmarkdown-it渲染文本
