### ISSUE TITLE
次数限制是不是问题

### ISSUE THREAD

**Issue by nongwoluanlai666** [vastsa/FileCodeBox#91]
如果直接访问地址下载就无视了次数限制  https://share.lanol.cn/share/download?key=ebf629cd5c65eb93e367d7d11dc1d4a6b0ad687e67f2ab3fb2585ac09f9e8a18&code=89897

**Comment by vastsa** [comment]
通过这个key，一定时间内可以直接下载，过期失效

**Comment by nongwoluanlai666** [comment]
ok
