### ISSUE TITLE
Feature suggestion - /admin page

### ISSUE THREAD

**Issue by Erkak** [vastsa/FileCodeBox#92]
Hello,

I have a couple of ideas for /admin page
1) On "File management" tab it would be nice to add "File size" column and also somewhere on the page show current size of whole file share
2) On "File management" tab it would be great to add "Client IP" column (Client IP, from which uploading file were performed)

Best regards

**Comment by vastsa** [comment]
ok

**Comment by vastsa** [comment]
1. File size column added
<img width="1615" alt="image" src="https://github.com/vastsa/FileCodeBox/assets/48862574/52bc18e0-60b3-4583-82bd-e9a8cd4fa6bd">
2. The shared file does not record IP information, so it cannot be added
