### ISSUE TITLE
S3存储容易暴露存储桶地址

### ISSUE THREAD

**Issue by Tslmuun** [vastsa/FileCodeBox#94]
开发者您好：

测试 S3存储引擎后发现，将文件发送给对方，容易暴露S3存储桶地址，容易被刷量攻击。

能否添加自定义域名，或者本地混淆下载链接？

**Comment by vastsa** [comment]
收到

**Comment by Do1e** [comment]
#108 中新增通过服务器代理下载的配置，不过缺点是用户需要等着服务器下载完成

**Comment by Do1e** [comment]
我不太懂s3，在OneDrive上做的测试。🥺

**Comment by Tslmuun** [comment]
这样似乎可以添加s3 hostname ，使用CDN了。我不会写代码，只是在本地测试了一下。
如果需要拿去改改添加就行。
https://github.com/Tslmuun/FileCodeBox/commit/a2692efa3ee3164816a648307b87499910698b6c
