### ISSUE TITLE
S3存储不支持SigV4 签名

### ISSUE THREAD

**Issue by Tslmuun** [vastsa/FileCodeBox#95]
开发者您好：

测试cloud flare R2 做为后端存储时取件下载出错。

`<Error>
<Code>Unauthorized</Code>
<Message>SigV2 authorization is not supported. Please use SigV4 instead.</Message>
</Error>`

请添加Signature Method选项以便支持亚马逊S3以及Cloudflare R2.

**Comment by vastsa** [comment]
收到
