### ISSUE TITLE
关于“系统管理-文件大小”的单位“bit”是否错误？

### ISSUE THREAD

**Issue by Dicartle** [vastsa/FileCodeBox#99]
10485760 Bytes 等于 10 MB
10485760 bit 等于 1.25MB
按照默认的配置文件里，默认文件是10MB。那么这在“系统管理-文件大小” 的说明里，单位应该是“Bytes”吧？

**Comment by vastsa** [comment]
收到，这就改

**Comment by Dicartle** [comment]
> 收到，这就改

更新了之后，/#/admin后台无法进去了？请大佬再看看，麻烦了。
